exclude: ^(dist/.*|CHANGELOG\.md|package-lock\.json)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        args: ['-b', main']
  - repo: https://github.com/executablebooks/mdformat
    rev: '0.7.13'
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-beautysh
          - mdformat-tables
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.8
    hooks:
      - id: actionlint-docker
        args: ['-ignore', 'property "path"']
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.9.0
    hooks:
      - id: eslint
        types: [ts]
  - repo: local
    hooks:
      - id: ncc
        name: ncc
        entry: npm run -- build
        language: system
        types: [ts]
        pass_filenames: false
