name: 'setup-binary'
description: cache and install a binary to $PATH
author: supplypike
inputs:
  uri:
    required: true
    description: download link for binary
  name:
    required: true
    description: name of binary
  version:
    required: true
    description: version of binary
  command:
    required: false
    description: install command (e.g make install)
  subPath:
    required: false
    description: path to tool in archive
  auth_username:
    required: false
    description: username to authenticate download
  auth_password:
    required: false
    description: password to authenticate download
runs:
  using: 'node12'
  main: 'dist/index.js'
