name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalr00ts/action-pre-commit@v0
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          uri: 'https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64'
          name: 'docker-compose'
          version: '1.27.4'
      - run: |
          which docker-compose
          docker-compose version
